cluster:
  mkdir -p logs/{rule} &&
  bsub
    -q {resources.partition}
    -n {threads}
    -R {resources.mem_mb}
    -J smk-{rule}-{wildcards}
    -o logs/{rule}/{rule}-{wildcards}-%j.out
    -W {resources.time}
    -P {resources.account}
    -M {resoruces.mem_mb}MB

default-resources:
  - partition=short
  - qos=normal
  - mem_mb=8000
  - time=120
  - account=re_gecip_cancer_pan

cluster-cancel: "lsf_cancel.py"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 200
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
use-singularity: True

# Bind this to the input directory containing the BAM files and output location if not default
# # Make sure these directories match out_dir and input_dir in the config.yml
# # Comment out these lines if not required.
singularity-args: "--bind /genomes/by_date --bind /re_scratch/re_gecip/cancer_pan/psmith2"
