# The main entry point of your workflow.
include: "rules/common.smk"

# file setup

def get_sample_bams(wildcards):
    return {
            'tumour': samples.loc[(wildcards.sample), ["tumour_bam"]].item(),
            'normal': samples.loc[(wildcards.sample), ["normal_bam"]].item()}

def get_sample_params(wildcards):
    return {
            'tumour_name':  samples.loc[(wildcards.sample), ["tumour_name"]].item(),
            'normal_name':  samples.loc[(wildcards.sample), ["normal_name"]].item(),
            'sex':  samples.loc[(wildcards.sample), ["sex"]].item(),
            'build':  samples.loc[(wildcards.sample), ["build"]].item()}

# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

localrules: all, combine

rule all:
    input:
        out_dir+"test_out.txt"
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

include: "rules/other.smk"

# Pipeline rules
include: "rules/ascat.smk"
include: "rules/combine.smk"
