# imports
from glob import glob

# The main entry point of your workflow.
include: "rules/common.smk"

# file setup
def get_sample_bams(wildcards):
    return {
            'tumour': samples.loc[(wildcards.sample), ["tumour_bam"]].item(),
            'normal': samples.loc[(wildcards.sample), ["normal_bam"]].item()}

def get_sample_params(wildcards):
    return {
            'tumour_name':  samples.loc[(wildcards.sample), ["tumour_name"]].item(),
            'normal_name':  samples.loc[(wildcards.sample), ["normal_name"]].item(),
            'sex':  samples.loc[(wildcards.sample), ["sex"]].item(),
            'build':  samples.loc[(wildcards.sample), ["build"]].item(),
            'cancer': samples.loc[(wildcards.sample), ["cancer"]].item(),
            'ploidy': samples.loc[(wildcards.sample), ["ploidy"]].item(),
            'purity': samples.loc[(wildcards.sample), ["purity"]].item()}

# Rules
localrules: all

rule all:
    input:
        expand(out_dir+"copy_number_signatures/{cancer}/cn_signatures.rds",cancer=cancersUniq),
        out_dir+"copy_number_signatures/cn_signatures.rds"

# Pipeline rules
include: "rules/ascat.smk"
include: "rules/combine_cancer.smk"
include: "rules/combine.smk"
include: "rules/get_signature_activities.smk"
include: "rules/get_signature_activities_cancer.smk"

