cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.time}
#    --account=default

default-resources:
  - partition=general
  - qos=normal
  - mem_mb=1000
  - time="02:00:00"
# - account=""

restart-times: 0 
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 200
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
use-singularity: True

# Bind this to the input directory containing the BAM files and output location if not default
# Make sure these directories match out_dir and input_dir in the config.yml
# Comment out these lines if not required.
singularity-args: "--bind /mnt/scratcha/fmlab/smith10/gel/bams --bind /mnt/scratcha/fmlab/smith10/gel"
