latency-wait: "15"
jobscript: "lsf_jobscript.sh"
use-conda: "False"
use-singularity: "true"
printshellcmds: "true"
restart-times: "0"
jobs: "200"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
cluster-cancel: "lsf_cancel.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"